# Lab2_2024

## 实验⽬标
- 掌握数值线性代数的⼀般算法：LU 分解、SOR
- 学会导⼊并使⽤数值计算库：numpy、scipy、matplotlib
- ⽣成实验⽤的数据和函数
- 学会使⽤线性代数建模并求解问题

## 实验方法
- 安装、调试python环境
- 生成线性方程组
- 使用SOR迭代法求解线性方程组

## 实验实现

In [1]:
import numpy as np
def generate_matrix(school_number):
    class_code = int(str(school_number)[-4:-2])
    individual_code = int(str(school_number)[-2:])
    n = class_code
    A = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            if i == j:
                A[i, j] = individual_code
            else:
                A[i, j] = (individual_code % (j+1)) / (n+1)
    b = np.array([(i + 1 + individual_code) * 2 for i in range(n)])
    return A, b

In [2]:
school_number = 23030320 # 换成你的学号
A, b = generate_matrix(school_number)
print("A:\n", A)
print("b:\n", b)

A:
 [[20.   0.   0.5]
 [ 0.  20.   0.5]
 [ 0.   0.  20. ]]
b:
 [42 44 46]


In [3]:
# from scipy.linalg import solve
# # 解线性⽅程组Ax = b
# x = solve(A, b)
# print(x) # 输出解向量

In [4]:
def sor(A, b, omega, initial_guess, tolerance=1e-10, max_iterations=1000):
    n = len(b)
    x = initial_guess.copy()
    for iteration in range(max_iterations):
        x_new = np.zeros_like(x)
        for i in range(n):
            s1 = np.dot(A[i, :i], x_new[:i])
            s2 = np.dot(A[i, i+1:], x[i+1:])
            x_new[i] = (b[i] - s1 - s2) / A[i, i]
            x_new[i] = (1 - omega) * x[i] + omega * x_new[i]
        
        if np.linalg.norm(x_new - x) < tolerance:
            return x_new, iteration
        
        x = x_new
    
    print("达到最⼤迭代次数，失败")
    return x, max_iterations

In [5]:
initial_guess = np.zeros(3)
omega = 1.5
solution, iterations = sor(A, b, omega, initial_guess)

print(f"解决方案: {solution}")
print(f"迭代次数: {iterations}")

解决方案: [2.0425 2.1425 2.3   ]
迭代次数: 38


## 实验总结
- 迭代法相比较直接法，虽然不能直接通过⼀系列精确的算术运算找到⽅程组的精确解，但是在处理⼤型稀疏矩阵，不要求精确解的情况下更为有效。